export const ImagePath = {
  line: require("../assets/image/line.png"),
  welcome: require("../assets/image/welcome.png"),
  bg1:require("../assets/image/bg1.png"),
  bg2:require("../assets/image/bg2.png"),
  image_2:require("../assets/image/imagebg.png"),
  dawadle: require("../assets/image/dawadle.png"),
  loginBottom: require("../assets/image/loginBottom.png"),
  lineReverse: require("../assets/image/loginLine.png"),
  googleIcon: require("../assets/image/googleLogo.png"),
  logoWhite: require("../assets/image/logoWhite.png"),
  quote: require("../assets/image/quote.png"),
  checked: require("../assets/image/checked.png"),
  r11: require("../assets/image/r11.png"),
  r12: require("../assets/image/r12.png"),
  r13: require("../assets/image/r13.png"),
  r14: require("../assets/image/r14.png"),
  r15: require("../assets/image/r15.png"),
  r21: require("../assets/image/r21.png"),
  r22: require("../assets/image/r22.png"),
  r23: require("../assets/image/r23.png"),
  r24: require("../assets/image/r24.png"),
  r25: require("../assets/image/r25.png"),
  r31: require("../assets/image/r31.png"),
  r32: require("../assets/image/r32.png"),
  r33: require("../assets/image/r33.png"),
  r34: require("../assets/image/r34.png"),
  r35: require("../assets/image/r35.png"),
  cry:require("../assets/image/Crying.png"),
  sad:require("../assets/image/Sad.png"),
  neutral:require("../assets/image/Neutral.png"),
  happy:require("../assets/image/Happy.png"),
  smile:require("../assets/image/Smiling.png"),
  image1: require("../assets/image/image1.jpeg"),
  image2: require("../assets/image/image2.jpg"),
  image3: require("../assets/image/image3.jpg"),
  image4: require("../assets/image/image4.jpg"),
  image5: require("../assets/image/image5.jpg"),
  whiteQuote:require("../assets/image/whiteQuote.png"),
  banner1:require("../assets/image/banner1.png"),
  banner2:require("../assets/image/banner2.png"),
  banner3:require("../assets/image/banner3.png"),
  banner4:require("../assets/image/banner4.png"),
  banner5:require("../assets/image/banner5.png"),
  checked:require("../assets/image/right.png"),
  feedbackIcon:require("../assets/image/FeedbackIcon.png"),
  taskList:require("../assets/image/taskList.png"),
  right:require("../assets/image/tick.png"),
};
